spring.application.name=bcap

logging.level.root=DEBUG
logging.level.com.example=ERROR  
logging.file.name=logs/spring-boot-application.log 

server.error.include.message: always
server.error.include.binding-errors: always
server.error.include.stacktrace: on_trace_param
server.error.include-exception: false