spring.application.name=bcap

logging.config=classpath:log4j2-spring.xml

aes.secret.key=ABCDEFGHIJKLMNOP
jwt_secret=3ZxNqN1V+7Tg4X5FZ9fD3+P0tU61KcLdNq8p0GZbG2w=

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload.path=D:/bcap

file.ext.filter=jpg,png,pdf,exe