spring.application.name=bcap
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
File.Path=E:/Work/SampleDoc

# Path di mana file akan diunggah
fileProp.File.Path=E:/Work/SampleDoc

# Daftar ekstensi file yang diizinkan, dipisahkan dengan koma (misalnya, jpg, png, pdf)
fileProp.File.Ext.FilterList=jpg,png,pdf