###
GET http://localhost:8080/

###
GET https://46bcf9717925.ngrok-free.app/bcap/

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "userId": "1787130271",
    "encryptionPassword": "7DB3C8AE5015726FB1B0120DCA9C6C7452279219553DCF4818C4DF885164463A",
    "screenId": "LOGIN",
    "appType": "I"
}

### Login
POST https://46bcf9717925.ngrok-free.app/bcap/auth/login
Content-Type: application/json

{
    "userId": "1787130271",
    "encryptionPassword": "7DB3C8AE5015726FB1B0120DCA9C6C7452279219553DCF4818C4DF885164463A",
    "screenId": "LOGIN",
    "appType": "I"
}

### Logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

{
    "userId": "1787130271",
    "screenId": "LOGOUT"
}

### Me (Authorized)
GET http://localhost:8080/auth/me4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJBdXRoSW5mbyI6eyJ1c2VySWQiOiIxNzg3MTMwMjcxIiwiZW5jcnlwdGlvblBhc3N3b3JkIjoiN0RCM0M4QUU1MDE1NzI2RkIxQjAxMjBEQ0E5QzZDNzQ1MjI3OTIxOTU1M0RDRjQ4MThDNERGODg1MTY0NDYzQSJ9LCJzdWIiOiIxNzg3MTMwMjcxIiwiZXhwIjoxNzYxNzIzNjQ0fQ.r0XWs2s8Gox1jviTNLYIsK_7UgEFvL7iO7RragGSQc0

### Message (call DeonC)
POST http://localhost:8080/message
Authorization: Bearer aaa

{
    "encryptedMessage": "aaa",
    "iv": "bbbb"
}