###
GET http://localhost:8080/

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "userId": "1787130271",
    "password": "@Yokkemti",
    "screenId": "LOGIN"
}

### Logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

{
    "userId": "1787130271",
    "screenId": "LOGOUT"
}

### Me (Authorized)
GET http://localhost:8080/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJBdXRoSW5mbyI6eyJ1c2VySWQiOiIxNzg3MTMwMjcxIiwicGFzc3dvcmQiOiJAWW9ra2VtdGkifSwic3ViIjoiMTc4NzEzMDI3MSIsImV4cCI6MTc1NTg0NTk5Mn0.nNHjSoMWm7jn_dm0YgoKv_vhWz8tD36tOv_XzzX-Q1o


